'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Alumno
    Public Property CodAlumno As Integer
    Public Property NombreApellido As String
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property Email As String
    Public Property FechaNacimiento As Nullable(Of Date)

    Public Overridable Property CursoAlumno As ICollection(Of CursoAlumno) = New HashSet(Of CursoAlumno)

End Class
