'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Curso
    Public Property CodCurso As Integer
    Public Property Descripcion As String
    Public Property CodModalidad As Integer
    Public Property CodFacultad As Integer
    Public Property FechaInicio As Nullable(Of Date)
    Public Property FechaFin As Nullable(Of Date)

    Public Overridable Property Facultad As Facultad
    Public Overridable Property Modalidad As Modalidad
    Public Overridable Property CursoAlumno As ICollection(Of CursoAlumno) = New HashSet(Of CursoAlumno)

End Class
