'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CursoAlumno
    Public Property CodCurso As Integer
    Public Property CodAlumno As Integer
    Public Property FechaMatriculacion As Date
    Public Property NotaFinal As Integer
    Public Property Observaciones As String

    Public Overridable Property Alumno As Alumno
    Public Overridable Property Curso As Curso

End Class
