'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Facultad
    Public Property CodFacultad As Integer
    Public Property Descripcion As String
    Public Property FechaFundacion As Nullable(Of Date)

    Public Overridable Property Curso As ICollection(Of Curso) = New HashSet(Of Curso)

End Class
