'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class FacuEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FacuEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Alumno() As DbSet(Of Alumno)
    Public Overridable Property Curso() As DbSet(Of Curso)
    Public Overridable Property CursoAlumno() As DbSet(Of CursoAlumno)
    Public Overridable Property Facultad() As DbSet(Of Facultad)
    Public Overridable Property Modalidad() As DbSet(Of Modalidad)

End Class
